# Generated by Django 4.2.2 on 2023-07-05 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OFs", "0003_alter_of_dp_alter_of_dp_version_alter_of_derogation"),
    ]

    operations = [
        migrations.AddField(
            model_name="of",
            name="Date_prévu",
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
        migrations.AddField(
            model_name="of",
            name="atelier",
            field=models.TextField(default="à determiner"),
        ),
    ]
