# Generated by Django 4.2.2 on 2023-07-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("OFs", "0004_of_date_prévu_of_atelier"),
    ]

    operations = [
        migrations.CreateModel(
            name="MP_OF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Reference", models.TextField(max_length=10)),
                ("N_LOT", models.TextField(max_length=20)),
                ("Quantite", models.IntegerField(default=0)),
                ("Matricule", models.IntegerField(default=0)),
                ("Statut", models.TextField(default="à prèparer", max_length=50)),
                (
                    "OF",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="OFs.of"
                    ),
                ),
            ],
        ),
    ]
