# Generated by Django 4.2.2 on 2023-07-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OFs", "0005_mp_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="of",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
