# Generated by Django 4.2.2 on 2023-07-06 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OFs", "0006_alter_of_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="of",
            name="Date_prévu",
            field=models.DateField(default=datetime.date(2023, 7, 6)),
        ),
    ]
