# Generated by Django 4.2.2 on 2023-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OFs", "0007_alter_of_date_prévu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="of",
            name="Derogation",
            field=models.TextField(default="aucune derogation", max_length=500),
        ),
    ]
