# Generated by Django 4.2.2 on 2023-07-09 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OFs", "0009_planningfile_alter_of_date_prévu"),
    ]

    operations = [
        migrations.AddField(
            model_name="of",
            name="Semaine_prévu",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="of",
            name="Date_prévu",
            field=models.DateField(default=datetime.date(2023, 7, 9)),
        ),
        migrations.AlterField(
            model_name="planningfile",
            name="file",
            field=models.FileField(upload_to="planning_files/"),
        ),
    ]
